### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by Savitar465** [Savitar465/task-manager#15]
![Image](https://github.com/user-attachments/assets/d6709dec-fddd-487b-b9ad-27980f159e61)

- [ ] Savitar465/users-service#3 
- [ ] Savitar465/users-service#9 
- [ ] Savitar465/users-service#6 
- [ ] Savitar465/users-service#5
